{% set name = "ele" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rsdefever/ele/archive/v{{ version }}.tar.gz
  sha256: 47b46551954b45be4b6a21fe04db7c1becc9565384de9de7dd5fe4ddb814f06e

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ele

about:
  home: https://github.com/rsdefever/ele
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'A lightweight package with the periodic table of the elements'
  description: |
    Ele is an extremely lightweight package that defines the elements of
    the periodic table and allows them to be accessed by symbol, name,
    atomic number, or mass. It has zero dependencies outside of the
    Python Standard Library.
  dev_url: https://github.com/rsdefever/ele

extra:
  recipe-maintainers:
    - rsdefever
